#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

patch -p8 $(find /opt/ironic-python-agent -wholename '*/proliantutils/hpssa/objects.py') < $(dirname $0)/../patch.txt
